package pageObjects;

public class ObjectRepository_HomePage {
	static String button_Login = "button_Login";
	static String textBox_emailId = "textBox_emailId";
	static String textBox_password = "textBox_password";
	static String button_signIn = "button_signIn";
	static String popUp_login = "popUp_login";
	static String textBox_firstName = "textBox_firstName";
	static String textBox_lastName = "textBox_lastName";
	static String textBox_MobileNo = "textBox_mobileNo";
	static String textBox_emailIdRegister = "textBox_emailIdRegister";
	static String textBox_passwordRegister = "textBox_passWordRegister";
	static String textBox_confirmPassWord = "textBox_confirmPassWord";
	static String link_Register = "link_Register";
	static String button_CloseLoginPoup = "button_CloseLoginPoup";
	static String button_register = "button_register";
	static String FirstProductFromCategory = "FirstProductFromCategory";
	static String checkBox_OnlyCODProducts = "checkBox_OnlyCODProducts";
	static String link_firstCategory = "link_firstCategory";
	static String button_buyNow = "button_buyNow";
	static String span_loginMessage = "span_loginMessage";
	static String text_loginMessage = "Invalid login or password.";
	static String button_proceedToPayment = "button_proceedToPayment";
	static String textBox_firstNameBillingInfo = "textBox_firstNameBillingInfo";
	static String textBox_lastNameBillingInfo = "textBox_lastNameBillingInfo";
	static String textBox_street1BillingInfo = "textBox_street1BillingInfo";
	static String textBox_street2BilligInfo = "textBox_street2BilligInfo";
	static String textBox_cityBilligInfo = "textBox_cityBilligInfo";
	static String textBox_postcodeBilligInfo = "textBox_postcodeBilligInfo";
	static String textBox_countryBilligInfo = "textBox_countryBilligInfo";
	static String textBox_regoinBilligInfo = "textBox_regoinBilligInfo";
	static String textBox_telephoneBillIngInfo = "textBox_telephoneBillIngInfo";
	static String button_continueOnCheckoutPage = "button_continueOnCheckoutPage";
	static String button_paymentCOD = "button_paymentCOD";
	static String button_homePageLogo = "button_homePageLogo";
	static String ListBox_countryBilligInfo = "ListBox_countryBilligInfo";
	static String ListBox_regoinBilligInfo = "ListBox_regoinBilligInfo";
	static String button_placeOrder = "button_placeOrder";
	static String span_loginErrorMessage = "span_loginErrorMessage";
	static String link_forgotPassWord = "link_forgotPassWord";
	static String textBox_forgotPassword = "textBox_forgotPassword";
	static String button_submitForgotPassword = "button_submitForgotPassword";
	static String span_forgotPasswordMessage = "span_forgotPasswordMessag";
	static String button_searchText = "button_searchText";
	static String Span_lastPageNo = "Span_lastPageNo";
	static String span_firstPage = "span_firstPage";
	static String link_allCategoryfromHomepage = "link_allCategoryfromHomepage";
	static String Button_addToWishList = "Button_addToWishList";
	static String Link_Account = "Link_Account";
	static String FirstProductFromWishlist = "FirstProductFromWishlist";
	static String feedPagesOnHomePage = "feedPagesOnHomePage";

}
